#!/usr/bin/env python3
"""Generate a machine-readable inventory of the RES201 workspace."""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path


def describe(rel_path: str, is_dir: bool) -> str:
    parts = rel_path.split("/")
    name = parts[-1]

    top_level = {
        ".codex": "Local Codex marker file for this workspace.",
        ".gitattributes": "Git attributes file used to route large binary artifacts through Git LFS.",
        "Project_Task": "Course and project reference PDFs.",
        "README.md": "Repository readme for the full shared RES201 workspace.",
        "cache": "Local cache area for downloaded resources.",
        "configs": "Saved experiment and debugging configuration files.",
        "data_shared": "Canonical oxide/nitride family datasets and derived exports.",
        "docs": "Project playbooks, status notes, and artifact guides.",
        "env": "Environment bootstrap and verification scripts.",
        "id_prop.csvtest_data": "Root-level LMDB cache generated by ALIGNN tooling for test data.",
        "id_prop.csvtrain_data": "Root-level LMDB cache generated by ALIGNN tooling for train data.",
        "id_prop.csvval_data": "Root-level LMDB cache generated by ALIGNN tooling for validation data.",
        "jv_formation_energy_peratom_alignn": "Pretrained ALIGNN checkpoint directory shared with collaborators.",
        "manifests": "Split manifests, templates, and conflict records.",
        "notebooks": "Notebook workspace reserved for later analysis.",
        "reports": "Report sources and generated workspace inventories.",
        "requirements": "Frozen dependency listings.",
        "res201_family_datasets_payload.README.txt": "Plain-language description of the portable family-dataset archive.",
        "res201_family_datasets_payload.zip": "Portable archive of the canonical family-dataset payload.",
        "results": "Zero-shot and fine-tuning experiment outputs.",
        "scripts": "Dataset and experiment automation scripts.",
    }
    if rel_path in top_level:
        return top_level[rel_path]

    if parts[0] == "Project_Task":
        pdf_map = {
            "RES201 Project.pdf": "Official course project brief and weekly deliverable specification.",
            "ALIGNN_Tutorial.pdf": "Tutorial/reference PDF for using ALIGNN.",
            "Project_Timeline_So_Far.pdf": "Human-maintained timeline and status summary for the project.",
        }
        return pdf_map.get(name, "Project reference document.")

    if parts[0] == "docs":
        doc_map = {
            "STAGE2_PLAYBOOK.md": "Instructions for Stage 2 dataset construction and validation.",
            "STAGE2_FROZEN_DATASET.md": "Notes describing the frozen Stage 2 dataset state.",
            "STAGE3_PLAYBOOK.md": "Instructions and expectations for Stage 3 training outputs.",
            "WORKSPACE_ARTIFACT_GUIDE.md": "Guide to the major artifact groups and naming conventions in the workspace.",
        }
        return doc_map.get(name, "Project documentation file.")

    if parts[0] == "env":
        env_map = {
            "bootstrap_res201_stage2_data.sh": "Shell script to create the Stage 2 data environment.",
            "verify_res201_stage2_data.py": "Python verifier for the Stage 2 data environment.",
            "bootstrap_res201_stage3_train.sh": "Shell script to create the Stage 3 training environment.",
        }
        return env_map.get(name, "Environment setup or verification script.")

    if parts[0] == "requirements":
        return "Frozen Python dependency listing for the training environment."

    if parts[0] == "manifests":
        manifest_map = {
            "dft_3d_formation_energy_peratom_splits.csv": "Official split manifest used for family filtering and evaluation.",
            "dft_3d_formation_energy_peratom_splits_conflicts.csv": "Conflict list for ambiguous split assignments excluded conservatively.",
            "original_split_manifest_template.csv": "CSV template for constructing a split manifest.",
            "original_split_manifest_template.json": "JSON template for constructing a split manifest.",
        }
        return manifest_map.get(name, "Manifest or split-template file.")

    if parts[0] == "cache":
        return "Cached JARVIS data or metadata."

    if parts[0] == "jv_formation_energy_peratom_alignn":
        checkpoint_map = {
            "README.md": "Quick orientation note for the pretrained ALIGNN checkpoint bundle.",
            "checkpoint_300.pt": "Local pretrained ALIGNN checkpoint used for Week 1.",
            "config.json": "Saved model configuration paired with the pretrained checkpoint.",
        }
        return checkpoint_map.get(name, "Pretrained checkpoint artifact.")

    if parts[0] == "configs":
        if name.endswith(".finetune_last2.json"):
            return "Final working Week 1 fine-tuning config for the specified family."
        if name.endswith(".fixed.json"):
            return "Schema-compatible config generated during debugging."
        if name.endswith(".run.json"):
            return "Historical run config from an intermediate debugging step."
        if name.endswith(".json"):
            return "Experiment configuration JSON."
        return "Configuration artifact."

    if parts[0] == "scripts":
        if len(parts) == 1:
            return "Root script directory."
        if parts[1] in {"oxide", "nitride"}:
            return "Reserved family-specific script directory."
        if parts[1] == "dataset":
            dataset_map = {
                "build_res201_family_datasets.py": "Build oxide and nitride family datasets from the benchmark split manifest.",
                "make_split_manifest_from_benchmark.py": "Construct a split manifest from benchmark identifiers.",
                "materialize_alignn_root.py": "Materialize ALIGNN-ready directory structures from manifests and structures.",
                "res201_stage2_lib.py": "Shared Stage 2 dataset-building library code.",
                "validate_res201_stage2.py": "Validate the frozen Stage 2 family datasets.",
            }
            return dataset_map.get(name, "Stage 2 dataset pipeline script.")
        if parts[1] == "shared":
            shared_map = {
                "zero_shot_alignn.py": "Run zero-shot pretrained ALIGNN evaluation on a family test set.",
                "prepare_week1_finetune_dataset.py": "Prepare the local Week 1 fine-tuning dataset root for a chosen family and N.",
                "write_week1_alignn_config.py": "Write a TrainingConfig-compatible ALIGNN config for Week 1 runs.",
                "finetune_last2_alignn.py": "Custom Week 1 fine-tuning wrapper that loads the pretrained checkpoint and unfreezes the final parameter groups.",
                "save_pretrained_state_dict.py": "Extract and save pretrained model state data.",
                "check_week1_status.sh": "End-to-end terminal checker for Week 1 completion.",
                "generate_workspace_inventory.py": "Generate a full CSV inventory of workspace files and folders.",
            }
            return shared_map.get(name, "Shared Week 1 experiment utility.")

    if parts[0] == "data_shared":
        if len(parts) == 2 and parts[1] == "diagnostics":
            return "Global Stage 2 diagnostics directory."
        if len(parts) >= 3 and parts[1] == "diagnostics":
            return "Global Stage 2 diagnostic artifact."
        if len(parts) == 2 and parts[1] in {"oxide", "nitride"}:
            return f"{parts[1].capitalize()} family dataset root."
        if len(parts) >= 3 and parts[2] == "manifests":
            manifest_desc = {
                "all.csv": "Full family manifest after applying the benchmark split first and family filter second.",
                "train.csv": "Frozen training manifest for this family.",
                "val.csv": "Frozen validation manifest for this family.",
                "test.csv": "Frozen held-out test manifest for this family.",
                "pool.csv": "Pool manifest used for N-subsampling during fine-tuning experiments.",
            }
            return manifest_desc.get(name, f"{parts[1].capitalize()} manifest file.")
        if len(parts) >= 3 and parts[2] == "summaries":
            return f"Saved Stage 2 summary for the {parts[1]} family."
        if len(parts) >= 3 and parts[2] == "structures":
            if is_dir:
                return f"Directory containing POSCAR structure files for the {parts[1]} family."
            return f"POSCAR structure file for one {parts[1]}-family material."
        if len(parts) >= 3 and parts[2] == "alignn_ready":
            if is_dir:
                return f"ALIGNN-ready export directory for the {parts[1]} family."
            return f"ALIGNN-ready export artifact for the {parts[1]} family."

    if parts[0] == "results":
        family = parts[1] if len(parts) > 1 else None
        if len(parts) == 2:
            return f"Top-level result directory for the {family} family."
        if len(parts) >= 3 and parts[2] == "zero_shot":
            if is_dir:
                return f"Zero-shot evaluation outputs for the {family} family."
            if name == "summary.json":
                return f"Zero-shot MAE summary for the {family} family."
            if name == "predictions.csv":
                return f"Per-example zero-shot predictions for the {family} family."
            return f"Zero-shot output artifact for the {family} family."
        if len(parts) >= 3 and parts[2].startswith("N"):
            run_name = parts[2]
            if len(parts) == 3:
                return f"Experiment root for the {family} {run_name} run."
            if len(parts) >= 4 and parts[3] == "dataset_root":
                if is_dir:
                    return f"Local ALIGNN dataset root for the {family} {run_name} fine-tuning run."
                if name == "id_prop.csv":
                    return f"ALIGNN id/target table for the {family} {run_name} run."
                if name == "split_manifest.json":
                    return f"Saved train/val/test allocation for the {family} {run_name} run."
                if name.endswith(".vasp"):
                    return f"Copied POSCAR structure for the {family} {run_name} run."
                return f"Dataset-root artifact for the {family} {run_name} run."
            if len(parts) >= 4 and parts[3] == "finetune_last2":
                if is_dir:
                    return f"Completed fine-tuning outputs for the {family} {run_name} run."
                fine_map = {
                    "config.json": "Resolved training config used for the completed fine-tuning run.",
                    "partial_finetune_meta.json": "Metadata describing which parameter groups were unfrozen.",
                    "history_train.json": "Per-epoch training history for the fine-tuning run.",
                    "history_val.json": "Per-epoch validation history for the fine-tuning run.",
                    "summary.json": "Compact summary of dataset sizes and final metrics for the fine-tuning run.",
                    "current_model.pt": "Current checkpoint saved during the fine-tuning run.",
                    "best_model.pt": "Best validation checkpoint from the fine-tuning run.",
                    "last_model.pt": "Final checkpoint after the fine-tuning run.",
                    "prediction_results_test_set.csv": "Per-example predictions on the fixed test set.",
                    "pred_data_test_set.csv": "Alias copy of the fixed test-set predictions.",
                    "prediction_results_train_set.csv": "Per-example predictions on the training split.",
                    "ids_train_val_test.json": "Explicit row allocation used to build train/val/test splits.",
                }
                if name.endswith("_data_range"):
                    return "LMDB cache directory produced from ALIGNN graph preprocessing."
                return fine_map.get(name, f"Fine-tuning artifact for the {family} {run_name} run.")
            if len(parts) >= 4 and parts[3] == "train_alignn_restart":
                return f"Historical restart-based training attempt for the {family} {run_name} run."

    if parts[0] == "reports":
        report_map = {
            "week1_report.tex": "Detailed Week 1 report source in LaTeX.",
            "workspace_inventory.csv": "Machine-generated inventory of every non-.git path in the workspace.",
            "workspace_inventory_summary.json": "Summary statistics for the generated workspace inventory.",
            "week1_report.pdf": "Compiled PDF version of the Week 1 report.",
            "week1_report.log": "LaTeX compilation log for the Week 1 report.",
            "week1_report.aux": "LaTeX auxiliary file for the Week 1 report.",
            "week1_report.out": "LaTeX hyperlink auxiliary file for the Week 1 report.",
        }
        return report_map.get(name, "Report-related artifact.")

    if parts[0].startswith("id_prop.csv") or name.startswith("data.mdb") or name.startswith("lock.mdb"):
        return "LMDB cache artifact produced during ALIGNN dataset preprocessing."

    if name.endswith(".json"):
        return "JSON metadata or summary artifact."
    if name.endswith(".csv"):
        return "CSV data artifact."
    if name.endswith(".md"):
        return "Markdown documentation file."
    if name.endswith(".py"):
        return "Python source file."
    if name.endswith(".sh"):
        return "Shell script."
    if name.endswith(".pt"):
        return "PyTorch checkpoint artifact."
    if name.endswith(".vasp"):
        return "POSCAR structure file."

    if is_dir:
        return "Directory."
    return "File."


def iter_find_rows(root: Path):
    for current_dir, dirnames, filenames in os.walk(root):
        current_path = Path(current_dir)
        dirnames[:] = sorted(d for d in dirnames if d != ".git")
        rel_dir = current_path.relative_to(root)
        if rel_dir != Path("."):
            yield rel_dir.as_posix(), True
        for filename in sorted(filenames):
            file_path = current_path / filename
            rel_file = file_path.relative_to(root)
            yield rel_file.as_posix(), False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--csv-out",
        type=Path,
        default=Path("reports/workspace_inventory.csv"),
    )
    parser.add_argument(
        "--summary-out",
        type=Path,
        default=Path("reports/workspace_inventory_summary.json"),
    )
    args = parser.parse_args()

    root = args.root.resolve()
    csv_out = args.csv_out
    summary_out = args.summary_out
    csv_out.parent.mkdir(parents=True, exist_ok=True)
    summary_out.parent.mkdir(parents=True, exist_ok=True)

    rows = []
    total_files = 0
    total_dirs = 0
    top_level_counts: dict[str, int] = {}

    for rel_path, is_dir in iter_find_rows(root):
        rows.append(
            {
                "path": rel_path,
                "kind": "dir" if is_dir else "file",
                "description": describe(rel_path, is_dir),
            }
        )
        if is_dir:
            total_dirs += 1
        else:
            total_files += 1
        top_key = rel_path.split("/", 1)[0]
        top_level_counts[top_key] = top_level_counts.get(top_key, 0) + 1

    with csv_out.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["path", "kind", "description"])
        writer.writeheader()
        writer.writerows(rows)

    summary = {
        "total_paths": len(rows),
        "total_files": total_files,
        "total_dirs": total_dirs,
        "top_level_counts": dict(sorted(top_level_counts.items())),
    }

    with summary_out.open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"wrote {csv_out}")
    print(f"wrote {summary_out}")
    print(f"total_paths={summary['total_paths']} total_files={total_files} total_dirs={total_dirs}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
